# Generated by Django 6.0.5 on 2026-08-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
    ]
