# Generated by Django 6.0.5 on 2026-07-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_book_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Книга", "verbose_name_plural": "Книги"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="shop_app.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/", verbose_name="Обкладинка"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кількість на складі"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Назва книги"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
        ),
    ]
